name: FancyNPCUtils
version: '${project.version}'
main: dev.floffah.plugin.fancynpcutils.FancyNPCUtils
api-version: 1.16
authors: [ Floffah ]
description: Fancy utilities for citizens
depend:
  - Citizens
